'use client'

import { useEffect, useMemo, useState } from 'react'

const files = [
  { key: 'dataset.py', stage: 'Dataset', status: 'implemented', purpose: 'Maps respiratory recordings and labels into a reproducible dataset interface.', input: 'ICBHI audio + annotations', output: 'Patient-aware samples', code: ['class RespiratoryDataset(Dataset):', '    def __init__(self, root_dir, transform=None):', '        self.samples = build_sample_index(root_dir)', '        self.transform = transform', '', '    def __getitem__(self, index):', '        path, label = self.samples[index]', '        audio, sr = load_audio(path)', '        return audio, label'] },
  { key: 'preprocessing.py', stage: 'Preprocessing', status: 'implemented', purpose: 'Normalizes the recording before feature extraction so examples share a stable shape.', input: 'Raw waveform', output: 'Normalized 5 s clip', code: ['def preprocess_audio(audio, sr):', '    audio = resample(audio, TARGET_SR)', '    audio = trim_or_pad(audio, TARGET_LENGTH)', '    audio = normalize(audio)', '    return audio'] },
  { key: 'features.py', stage: 'Features', status: 'implemented', purpose: 'Turns time-domain breathing into a compact visual representation for the network.', input: 'Normalized waveform', output: 'Mel / MFCC tensor', code: ['def extract_features(audio, sr):', '    mel = librosa.feature.melspectrogram(', '        y=audio, sr=sr, n_mels=N_MELS', '    )', '    mfcc = librosa.feature.mfcc(y=audio, sr=sr)', '    return stack_features(mel, mfcc)'] },
  { key: 'model.py', stage: 'Model', status: 'implemented', purpose: 'Combines local spectral cues with temporal context and an attention readout.', input: 'Feature sequence', output: 'Class logits', code: ['backbone = EfficientNetB0(weights="imagenet")', 'temporal = Bidirectional(LSTM(128,', '    return_sequences=True))(features)', 'context = Attention()([temporal, temporal])', 'logits = Dense(NUM_CLASSES, activation="softmax")(context)'] },
  { key: 'train.py', stage: 'Training', status: 'implemented', purpose: 'Trains in two deliberate phases: stabilize the head, then fine-tune the backbone.', input: 'Features + labels', output: 'Checkpoint', code: ['for layer in backbone.layers:', '    layer.trainable = False', 'model.fit(train_loader, validation_data=val_loader)', '', 'for layer in backbone.layers:', '    layer.trainable = True', 'model.fit(train_loader, validation_data=val_loader)'] },
  { key: 'evaluate.py', stage: 'Evaluation', status: 'implemented', purpose: 'Measures performance at the patient level and exposes the operating point.', input: 'Predictions + labels', output: 'Metrics + curves', code: ['probs = model.predict(test_loader)', 'preds = (probs[:, 1] >= threshold).astype(int)', 'report = classification_report(labels, preds)', 'roc = roc_curve(labels, probs[:, 1])', 'return report, roc'] },
  { key: 'predict.py', stage: 'Prediction', status: 'documented', purpose: 'Connects a new audio file to the same preprocessing and model path.', input: 'New respiratory audio', output: 'Probability vector', code: ['audio, sr = load_audio(path)', 'features = extract_features(', '    preprocess_audio(audio, sr), sr)', 'probability = model.predict(features)', 'return format_prediction(probability)'] },
]

const architecture = [
  ['01', 'Patient split', 'Keep recordings from one patient in one fold to reduce leakage.'],
  ['02', 'Spectral view', 'Mel and MFCC features make breathing texture visible to the encoder.'],
  ['03', 'Temporal memory', 'BiLSTM reads how respiratory events evolve across the clip.'],
  ['04', 'Attention readout', 'The model can weight the most informative moments before classification.'],
]

export function CopdDetectionLab() {
  const [activeKey, setActiveKey] = useState(files[0].key)
  const [playing, setPlaying] = useState(false)
  const active = useMemo(() => files.find(file => file.key === activeKey) ?? files[0], [activeKey])
  const activeIndex = files.findIndex(file => file.key === active.key)
  const selectOffset = (offset: number) => setActiveKey(files[(activeIndex + offset + files.length) % files.length].key)
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setActiveKey(key => { const index = files.findIndex(file => file.key === key); return files[(index + 1) % files.length].key }), 2600); return () => window.clearInterval(timer) }, [playing])

  return <section className="copd-lab" aria-labelledby="copd-lab-title">
    <div className="copd-lab-kicker"><span><i /> DOCUMENTATION MODE / FRONTEND EXPLAINER</span><span>NO MODEL EXECUTION</span></div>
    <div className="copd-lab-hero"><div><p className="tiny-label">COPD Detection Lab</p><h2 id="copd-lab-title">Read the model<br /><em>as a story.</em></h2><p>Follow the uploaded Python project from respiratory audio to a documented prediction path. This is an explainer for the system—not a clinical tool and not a live inference runtime.</p></div><div className="lab-hero-signal" aria-hidden="true"><div className="lab-signal-grid" />{Array.from({ length: 34 }, (_, index) => <i key={index} style={{ height: `${24 + ((index * 31) % 68)}%` }} />)}<strong>audio → probability</strong></div></div>
    <div className="lab-flow" role="tablist" aria-label="Project pipeline files">{files.map((file, index) => <button key={file.key} role="tab" aria-selected={active.key === file.key} className={active.key === file.key ? 'active' : ''} onClick={() => setActiveKey(file.key)}><span>{String(index + 1).padStart(2, '0')}</span><b>{file.stage}</b><small>{file.key}</small></button>)}</div>
    <div className="lab-workspace"><div className="lab-code-pane"><div className="lab-pane-head"><span><i className="file-dot" />{active.key}</span><span className={`lab-status ${active.status}`}>{active.status}</span></div><pre aria-label={`Documentation excerpt from ${active.key}`}>{active.code.map((line, index) => <code key={`${active.key}-${index}`} className={line.includes('def ') || line.includes('class ') || line.includes('model.') || line.includes('return ') ? 'highlight' : ''}><span>{String(index + 1).padStart(2, '0')}</span>{line || ' '}</code>)}</pre><div className="lab-code-foot"><span>Python / project artifact</span><span>Excerpt for explanation</span></div></div><div className="lab-story-pane"><span className="tiny-label">{active.stage} / what happens here</span><h3>{active.purpose}</h3><div className="lab-io"><div><small>INPUT</small><b>{active.input}</b></div><span>→</span><div><small>OUTPUT</small><b>{active.output}</b></div></div><div className="lab-story-note"><span>↳</span><p><strong>Why this matters</strong>{active.stage === 'Dataset' ? ' Patient-aware indexing is the foundation for trustworthy evaluation.' : active.stage === 'Model' ? ' Each block has a distinct job: image-like features, sequence context, then a focused readout.' : active.stage === 'Evaluation' ? ' Metrics turn a score into evidence that can be inspected and challenged.' : ' The next stage receives a defined representation, keeping the project explainable.'}</p></div><div className="lab-controls"><button className="text-button" onClick={() => selectOffset(-1)}>← Previous</button><button className="lab-play" onClick={() => setPlaying(value => !value)} aria-pressed={playing}>{playing ? 'Pause story' : 'Play story'} <span>{playing ? 'Ⅱ' : '▶'}</span></button><button className="text-button" onClick={() => selectOffset(1)}>Next →</button></div></div></div>
    <div className="lab-architecture"><div><p className="tiny-label">Architecture notes</p><h3>The design decisions<br /><em>behind the code.</em></h3></div><div className="architecture-notes">{architecture.map(([number, title, text]) => <article key={number}><span>{number}</span><div><h4>{title}</h4><p>{text}</p></div></article>)}</div></div>
    <div className="lab-disclaimer"><span>!</span><p><strong>Documentation boundary</strong>This frontend presents the supplied code as an educational research artifact. It does not run the model, validate medical claims, or provide a diagnosis.</p></div>
  </section>
}
