'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

const samples = [
  { name: 'COPD / wheeze', file: 'DP62_COPD_EW_PLM_53_M.wav', label: 'Wheeze', confidence: 86, cue: 'Continuous tonal bands', band: '400–1,200 Hz', timing: 'Sustained expiration', note: 'A musical, narrow-band pattern that persists across the breath.' },
  { name: 'COPD / wheeze', file: 'DP61_COPD_EW_PRL_53_M.wav', label: 'Wheeze', confidence: 84, cue: 'Continuous tonal bands', band: '400–1,200 Hz', timing: 'Sustained expiration', note: 'A musical, narrow-band pattern that persists across the breath.' },
  { name: 'COPD / mixed signal', file: 'DP25_COPD_EW_PLL_76_M.wav', label: 'Mixed', confidence: 79, cue: 'Mixed tonal and transient events', band: 'Broadband impulses', timing: 'Across breath cycle', note: 'A reference COPD recording with multiple acoustic features.' },
  { name: 'Normal / anterior left', file: '101_1b1_Al_sc_Meditron.wav', label: 'Normal', confidence: 94, cue: 'Low-noise airflow', band: 'Broad / low energy', timing: 'Smooth inhale → exhale', note: 'A clean reference signal with no dominant adventitious event.' },
  { name: 'Normal / anterior right', file: '102_1b1_Ar_sc_Meditron.wav', label: 'Normal', confidence: 93, cue: 'Low-noise airflow', band: 'Broad / low energy', timing: 'Smooth inhale → exhale', note: 'A clean reference signal with no dominant adventitious event.' },
]
const stages = ['Load audio', 'Resample 16 kHz', 'Build spectrogram', 'Run classifier']
const bars = Array.from({ length: 72 }, (_, i) => 18 + ((i * 31) % 64))

export function PlaygroundDemo() {
  const [sample, setSample] = useState(0)
  const [query, setQuery] = useState('')
  const [model, setModel] = useState('CNN + BiLSTM + Attention')
  const [view, setView] = useState<'waveform' | 'spectrogram'>('waveform')
  const [running, setRunning] = useState(false)
  const [stage, setStage] = useState(3)
  const [playing, setPlaying] = useState(false)
  const [progress, setProgress] = useState(0)
  const [audioError, setAudioError] = useState(false)
  const [uploaded, setUploaded] = useState<{ name: string; url: string } | null>(null)
  const [history, setHistory] = useState<string[]>([])
  const [focusMode, setFocusMode] = useState(false)
  const [showDetails, setShowDetails] = useState(true)
  const audioRef = useRef<HTMLAudioElement>(null)
  const current = samples[sample]
  const filtered = useMemo(() => samples.filter(item => `${item.name} ${item.file} ${item.label}`.toLowerCase().includes(query.toLowerCase())), [query])
  const source = uploaded?.url || `/audio/${current.file}`

  useEffect(() => { setPlaying(false); setProgress(0); setAudioError(false); audioRef.current?.pause(); audioRef.current?.load() }, [sample, uploaded?.url])
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Enter' && (event.metaKey || event.ctrlKey) && !running) run() }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) }, [running, uploaded?.name, current.file])
  const reset = () => { setRunning(false); setStage(3); setPlaying(false); setProgress(0); audioRef.current?.pause() }
  const run = () => { reset(); setRunning(true); setStage(0); let n = 0; const timer = window.setInterval(() => { n += 1; setStage(n); if (n >= 3) { window.clearInterval(timer); window.setTimeout(() => { setRunning(false); setHistory(items => [uploaded?.name || current.file, ...items].slice(0, 3)) }, 600) } }, 520) }
  const chooseFile = (file?: File) => { if (!file || !file.type.startsWith('audio/')) return; if (uploaded) URL.revokeObjectURL(uploaded.url); setUploaded({ name: file.name, url: URL.createObjectURL(file) }); reset() }

  return <section className={`flagship-playground${focusMode ? ' focus-mode' : ''}`} aria-label="Interactive respiratory model playground">
    <div className="playground-command-bar"><div><span className="eyebrow-dot" />LIVE RESEARCH SURFACE <b>v0.3</b></div><div className="command-status"><span className="status-dot" />{running ? 'INFERENCE ACTIVE' : 'MODEL READY'}<i /></div></div>
    <div className="playground-layout">
      <aside className="playground-sidebar">
        <div className="sidebar-heading"><div><span className="tiny-label">01 / Signal library</span><h2>Recordings</h2></div><span className="count-badge">{samples.length}</span></div>
        <div className="library-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter recordings" aria-label="Filter recordings" /></div>
        <div className="sample-list">{filtered.map(item => { const index = samples.indexOf(item); return <button key={item.file} className={sample === index && !uploaded ? 'sample-row active' : 'sample-row'} onClick={() => { setUploaded(null); setSample(index); reset() }}><span className="sample-index">{String(index + 1).padStart(2, '0')}</span><span><b>{item.label}</b><small>{item.file}</small></span><em>{item.confidence}%</em></button> })}</div>
        <motion.label whileHover={{ scale: 1.02, backgroundColor: 'var(--mint)' }} className="upload-zone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); chooseFile(e.dataTransfer.files[0]) }}><span className="upload-glyph">↑</span><span><b>{uploaded ? 'Custom audio loaded' : 'Drop your recording'}</b><small>{uploaded?.name || 'WAV, MP3, M4A · up to 30 sec'}</small></span><input type="file" accept="audio/*,.wav,.mp3,.m4a" onChange={e => chooseFile(e.target.files?.[0])} aria-label="Upload your respiratory audio" /></motion.label>
        <div className="sidebar-note"><span>i</span><p>Use a short, quiet recording for this research demonstration. No files leave your browser.</p></div>
      </aside>
      <main className="playground-console">
        <header className="console-header"><div><span className="tiny-label">02 / Analysis console</span><h1>{uploaded?.name || current.file}</h1><p>{uploaded ? 'Local upload · ready for feature extraction' : `${current.name} · reference recording`}</p></div><div className="console-actions"><button className="icon-action" onClick={() => setFocusMode(value => !value)} aria-pressed={focusMode}>{focusMode ? 'Exit focus' : 'Focus view'}</button><button className="icon-action" onClick={() => setShowDetails(value => !value)} aria-expanded={showDetails}>{showDetails ? 'Hide detail' : 'Show detail'}</button><button className="icon-action" onClick={() => navigator.clipboard?.writeText(window.location.href)} aria-label="Copy playground link" title="Copy playground link">↗</button><button className="text-button" onClick={reset} title="Reset analysis">Reset</button></div></header>
        <div className="analysis-status" role="status" aria-live="polite"><span className={running ? 'status-dot active' : 'status-dot'} />{running ? `Pipeline active · ${stages[Math.min(stage, stages.length - 1)]}` : uploaded ? 'Local audio loaded · ready to analyze' : 'Reference signal selected · ready to analyze'}<b>{running ? `${Math.min(stage + 1, stages.length)}/${stages.length}` : 'READY'}</b></div>
        <div className="signal-stage"><div className="stage-toolbar"><div className="view-switcher" role="tablist" aria-label="Signal view"><button className={view === 'waveform' ? 'active' : ''} onClick={() => setView('waveform')} role="tab" aria-selected={view === 'waveform'}>Waveform</button><button className={view === 'spectrogram' ? 'active' : ''} onClick={() => setView('spectrogram')} role="tab" aria-selected={view === 'spectrogram'}>Spectrogram</button></div><span className="readout">{playing ? `${progress.toFixed(0)}% · LIVE` : '5.0 SEC · 16 KHZ'}</span></div><div className={view === 'spectrogram' ? 'signal-visual spectrogram' : 'signal-visual'}>{bars.map((height, i) => <i key={i} style={{ height: `${view === 'spectrogram' ? 25 + ((i * 17) % 70) : height}%`, opacity: progress > i / bars.length ? 1 : .5 }} />)}<span className="scan-line" /></div><div className="signal-axis"><span>00:00</span><span>Inspiration / expiration</span><span>00:05</span></div><div className="audio-deck"><button className="audio-play" onClick={async () => { const audio = audioRef.current; if (!audio) return; if (audio.paused) { try { setAudioError(false); await audio.play(); setPlaying(true) } catch { setAudioError(true) } } else { audio.pause(); setPlaying(false) } }} aria-label={playing ? 'Pause audio' : 'Play audio'}>{playing ? 'Ⅱ' : '▶'}</button><input type="range" min="0" max="100" value={progress} onChange={e => { const value = Number(e.target.value); setProgress(value); if (audioRef.current?.duration) audioRef.current.currentTime = audioRef.current.duration * value / 100 }} aria-label="Audio progress" /><span aria-live="polite">{audioError ? 'Audio unavailable — retry' : playing ? 'Listening live' : 'Listen to signal'}</span><audio ref={audioRef} src={source} preload="metadata" onTimeUpdate={e => { const a = e.currentTarget; setProgress(a.duration ? a.currentTime / a.duration * 100 : 0) }} onEnded={() => setPlaying(false)} onError={() => { setPlaying(false); setAudioError(true) }} /></div></div>
        <div className="console-grid"><section className="pipeline-card"><div className="card-heading"><span className="tiny-label">03 / Processing pipeline</span><span className={running ? 'live-label active' : 'live-label'}>{running ? 'RUNNING' : 'IDLE'}</span></div><div className="pipeline-track">{stages.map((item, i) => <div className={i <= stage ? 'pipeline-step done' : 'pipeline-step'} key={item}><span>{i < stage ? '✓' : String(i + 1).padStart(2, '0')}</span><b>{item}</b><small>{i === 0 ? '44.1 kHz' : i === 1 ? 'mono' : i === 2 ? '128 × 96' : '4 classes'}</small></div>)}</div><motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} className="run-button" onClick={run} disabled={running}><span className="run-icon">{running ? '◌' : '→'}</span>{running ? 'Extracting features…' : 'Run prediction'}<kbd>⏎</kbd></motion.button></section><section className="model-card"><div className="card-heading"><span className="tiny-label">04 / Model controls</span><span className="model-live">CHECKPOINT READY</span></div><label>Architecture<select value={model} onChange={e => setModel(e.target.value)}><option>CNN + BiLSTM + Attention</option><option>EfficientNet baseline</option><option>MFCC + dense classifier</option></select></label><div className="model-stats"><div><b>128</b><small>features</small></div><div><b>16k</b><small>sample rate</small></div><div><b>4</b><small>classes</small></div></div></section></div>
        <motion.section layout transition={{ duration: 0.3 }} className={running ? 'result-card analyzing' : 'result-card'}><div className="result-heading"><div><span className="tiny-label">05 / Model output</span><h2>{running ? 'Reading acoustic signature…' : current.label}</h2></div><span className="confidence-ring">{running ? '…' : `${current.confidence}%`}</span></div><div className="confidence-bars"><div><span>Normal</span><i><b style={{ width: `${current.label === 'Normal' ? current.confidence : 8}%` }} /></i><strong>{current.label === 'Normal' ? current.confidence : 8}%</strong></div><div><span>Wheeze</span><i><b style={{ width: `${current.label === 'Wheeze' ? current.confidence : 18}%` }} /></i><strong>{current.label === 'Wheeze' ? current.confidence : 18}%</strong></div><div><span>Crackle</span><i><b style={{ width: `${current.label === 'Mixed' ? 42 : 11}%` }} /></i><strong>{current.label === 'Mixed' ? 42 : 11}%</strong></div></div><p className="result-note">{running ? 'The prototype is comparing spectral and temporal features.' : current.note}</p></motion.section>
        {showDetails && <div className="lower-grid"><section className="evidence-card"><span className="tiny-label">06 / Explainability</span><h3>Why this output?</h3><div className="evidence-chips"><span>spectral band</span><span>event timing</span><span>tonal continuity</span></div><p>{current.cue}. The highlighted cues are research signals, not a clinical diagnosis.</p></section><section className="history-card"><div className="card-heading"><span className="tiny-label">07 / Recent runs</span><span>{history.length}/3</span></div>{history.length ? history.map((item, i) => <div className="history-row" key={`${item}-${i}`}><span>{String(i + 1).padStart(2, '0')}</span><b>{item}</b><small>complete</small></div>) : <p className="empty-history">Run a sample to create a local analysis trail.</p>}</section></div>}
        <footer className="research-footer"><span>RESEARCH DEMONSTRATION · NOT FOR DIAGNOSIS</span><span>No upload leaves this browser</span></footer>
      </main>
    </div>
  </section>
}
